### ISSUE TITLE
unsolved dependency with 5.14.6 kernel - libc6 >=2.34 in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by edmundlaugasson** [bkw777/mainline#106]
Currently not possible to install newest kernel 5.14.6 as in [latest Ubuntu LTS is still v2.31, although in Ubuntu 21.10 presumably will be v2.34,](https://packages.ubuntu.com/search?keywords=libc6&searchon=names&suite=all&section=all) but it is not LTS, therefore not used in mission critical computers. Would it be possible to solve? E.g. add newer libc6...

EDIT: found - https://askubuntu.com/questions/1334633/mainline-kernel-now-depends-on-libc6-2-33-non-installable-in-focal
These repos are free from that dependency:
* for 5.14.x - https://launchpad.net/%7Etuxinvader/+archive/ubuntu/lts-mainline
* for 5.10.x - https://launchpad.net/%7Etuxinvader/+archive/ubuntu/lts-mainline-longterm

**Comment by bkw777** [comment]
It has always been the case since day one (ie, long before any convenience front-end app like this ever existed) that any given mainline kernel package might not be usable on any given system. This libc thing is just one of countless possible reasons. The only answer to this, right from the mainline-ppa site itself since day one has only ever been (paraphrased) "If a kernel package doesn't work, then modify your system to be compatible, or don't use it, there is no support or promises".

https://wiki.ubuntu.com/Kernel/MainlineBuilds

So, if they change the way the packages are built, and we can't upgrade dependecies to match, then we can't use those packages, simple as that.

It's outside the scope of a .deb installer like this (or muon/aptitude/synaptic/etc) to try to analyse a package and predict whether it will work on the users system. The scope of this app is only: Download .debs and run dpkg -i . That's it.

We might possibly make the main download url into a configurable option so that you could download from an alternate source like those tuxraiser ppa's but then the problem is, half of what this app des is parse the index.html's and directoris on the mainline-ppa site. So an alternative url would only work if the alternate site replicates all the same directory structure and index.htmls and other files just like the mainline-ppa site.

For an ordinary ppa, just install the ppa like any other ppa and you don't need an app like this to stay up to date.

**Comment by edmundlaugasson** [comment]
I thought your app is meant to use, which currently isn't possible with newer kernels. I thought you can fix it or know, who can. Just closing issue doesn't solve it... As you see, there is already someone from community, who fixed the issue and proposed own repo for that. This issue renders mainline app useless for Ubuntu 20.04 LTS if it cannot be fixed by Canonical.

**Comment by bkw777** [comment]
You don't seem to understand what's going on, despite my explaination. You want something which doesn't exist. No one from the community "fixed this issue" They simply compiled the kernels themselves in a different environment from what the mainline-ppa web site uses. That in no way resolves the problem that the mainline-ppa site produces kernel packages that aren't installabe on every system.

If you want to build the kernels frm sources, or use some other PPA where someone else did that, go ahead. It has nothing to do with this app. When you use a reglar PPA, you don't need this app. You can just use Muon or Synaptic etc. This app's only reason for existing is to deal with the fact that the mainline-ppa site is NOT a normal PPA and can't be installed in apt like other repos.

**Comment by edmundlaugasson** [comment]
Sorry, but you seem not to understand, what I understood (or know). I understand pretty well, what people did and how repos work. Just mention with current issue, that newer kernels cannot be installed with current latest Ubuntu LTS (either with or without your software). As you deal more with kernels, then perhaps you know right people to communicate, so it could be fixed at mainline-ppa site. I posted in [Ubuntu Kernel Team](https://wiki.ubuntu.com/KernelTeam) IRC but it might not the way to reach right people. At the same time it is weird, that Canonical doesn't support their current latest LTS-version...
