### ISSUE TITLE
po fuzzy

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#111]
how to fix the situation with translations marked #, fuzzy ?

**Comment by bkw777** [comment]
What situation?

**Comment by bkw777** [comment]
What?

**Comment by cappelikan** [comment]
I say that I understood the problem

**Comment by bkw777** [comment]
So is there an issue? Shall we close this?

**Comment by cappelikan** [comment]
Unfortunately, I can't make a very short translation because it has nothing to do with the rules of the language, so maybe it will be long but correct with the rules of the language or not?

**Comment by bkw777** [comment]
It's a button, there just isn't room for a sentence, only a word or two. There's really no way to express the concept?

I don't even like "uninstall old" because even that is two words and really a button should just be one. I only changed it because some people complained that "purge was confusing because "purge" already has a special meaning in the context of apt/dpkg, which is "dpkg --purge", which is not what that button does. And I agree with the complaint, it is confusing.

But outside of the context of apt/dpkg, the ordinary meaning of "purge" is reasonable for what the button does. It's vague, and needs the tooltip to explain it, but with the explaination it does fit. Almost like "flush" or "clean".

Is there any other way to express the idea of "remove excess" ? It doesn't have to literally translate the two words "uninstall old" if those exact words don't make sense in Ukrainian.

I suppose if there is really no other way, you can even put it back to "Purge" and we'll rely on the tooltip to explain that it doesn't mean "dpkg --purge". Now that I think about it, after all, in any other language besides English, that confusion probably doesn't exist in the first place, because "purge" in any other language is not "purge" and perhaps causes no confusion with "dpkg --purge" ?

**Comment by cappelikan** [comment]
I understood the situation. then I translate easier than I have

**Comment by cappelikan** [comment]
I shortened the translation as best I could, Brian please passed me the controversial translation terms marked as fuzzy so I could think again about how to rework them, cut

**Comment by bkw777** [comment]
Also, I wish to try to use "un-install" rather than "remove" or "delete" if possible, to distinguish between merely removing from the list or de-selecting vs un-installing, IE, removing from the system. If there is no better word than Delete, I'll take your word for it, but just so you know what I'm trying to express.

**Comment by cappelikan** [comment]
Can enter a deadline for removal from the list?

**Comment by bkw777** [comment]
I don't know what you're trying to say.

**Comment by cappelikan** [comment]
it seems that only un-install remains
