### ISSUE TITLE
installing 5.16.16-051616-generic on 18.04.6 with dependency issues  

### ISSUE THREAD

**Issue by PaulRehel** [bkw777/mainline#132]
Ubuntu 18.04.6 LTS using Nvidia 510.54 installing 5.16.16-051616-generic on  with dependency issues :
linux-headers-5.16.16-051616-generic depends on libc6 (>= 2.34); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.5.
 linux-headers-5.16.16-051616-generic depends on libssl3 (>= 3.0.0~~alpha1); however:
  Package libssl3:amd64 is not installed.
dpkg: error processing package linux-headers-5.16.16-051616-generic (--install)
ERROR (dkms apport): kernel package linux-headers-5.16.16-051616-generic is not supported
Error! Bad return status for module build on kernel: 5.16.16-051616-generic (x86_64)
Consult /var/lib/dkms/nvidia/510.54/build/make.log for more information.

**Comment by bkw777** [comment]
As the message from dpkg says, the package requires things you don't have.

This is because the mainline-ppa kernel packages don't support systems as old as 18.04 any more. It's not something this app controls. The kernel packages are built by the mainline-ppa maintainers. All this app does is download them and run "dpkg -i" to install them, same as you would do manually.

If you want to use a mainline-ppa kernel package, you will have to meet those dependencies one way or another. The normal way would be by updating to at least Impish, and then installing a libssl3 package from Jammy on top of that:
https://github.com/bkw777/mainline/wiki/Install-libssl3

Without updating your system to Impish, or possibly at least hirsuit, you would have to install at least both libc and libssl3 from Jammy, and I doubt that would work very well on 18.04,. You could try it, see the doc above and follow the link to a Jammy repo to download packages manually, but I don't recommend it, it will probably try to pull down even more dependencies and make a mess of your system.

If you can't do that, then you can't use any mainline-ppa packages that were built in about the last year.
