### ISSUE TITLE
ADD ability to set title/comment for (uninstalled) kernels

### ISSUE THREAD

**Issue by allanlaal** [bkw777/mainline#133]
# use case:

I can keep track of what I've tested and why they didn't work out for me

# scope:

mainline cli
(mainline-gtk)

**Comment by allanlaal** [comment]
# use case:

bisecting a lost feature


# current alternative:

notepad & "where the f did I write those down" :D

**Comment by bkw777** [comment]
Not a terrible idea.

**Comment by ibrahimBeladi** [comment]
It can be worked around using a text file. But it would be helpful to be inside the application without the need of an external logging.

I lived through this. I had an issue, so I bisected the versions until I spotted the broken patch version. I waited until it was resolved in a minor version. I restarted like 5 or 6 times until I found that broken version.

**Comment by bkw777** [comment]
For now I've replaced the Changes button with Notes which just opens a notes.txt for that kernel instead of changes.
I know that isn't actually all that useful since the notes don't show in the list. It's no better than just maintaining your own plain txt file. Also they get deleted along with the rest of the cache if your press Reload. But it was trivial so why not.

But I think next I'll work on a text field that can display right in the list and be edited by clicking on it, and a few per-kernel toggles for whitelist/blacklist/keep etc. I think the first line or the first N bytes will show right in the list, and the rest will show in the hover tooltip or when you click on it to edit.

**Comment by bkw777** [comment]
the list now includes a notes field which is editable
