### ISSUE TITLE
Missing keys required for secure boot?

### ISSUE THREAD

**Issue by craigcarnell** [bkw777/mainline#150]
I've updated to the latest version however after selecting Kernel 5.19.2 on a clean Ubuntu 22.04.1 install it reboots with:

"error: bad shim signature.
error: you need to load the kernel first.

Press any key to continue..."

Secure boot is enabled.

**Comment by bkw777** [comment]
See #52
Disable secure boot, or don't use kernels from kernel.ubuntu.com (what this app fetches).

Or read up on how to sign your own kernels and add your own signatures to your bios. Nnon-trivial, I don't actually suggest that is remotely practical. Or maybe there's some way to make your own signed grub instead of kernel, same problem. Above are your real choices.

In any event, it actually has nothing to do with this app, this is just a package downloader and dpkg-runner like synaptic. If the kernel turns out not to work it just means you should remove that kernel. We don't touch the bootloader, and we don't create the kernel packages, and there is no way to validate them any better than what already happens naturally by dpkg when it checks dependencies at install-time. IE there is no way to test for the infinite number of ways a new kernel might not work. Even the authors of the kernel packages themselves only say this:
From https://wiki.ubuntu.com/Kernel/MainlineBuilds :
"Support (BEWARE: there is none)
The mainline kernel builds are produced for debugging purposes and therefore come with no support. Use them at your own risk."
