### ISSUE TITLE
Not deleting old Kernel Modules (foldet not empty)

### ISSUE THREAD

**Issue by Danik2343** [bkw777/mainline#151]
Not deleting old Kernel Modules (foldet not empty) (wrong command syntax)
![изображение](https://user-images.githubusercontent.com/38865696/185805130-f16030d3-f0fd-4c1e-87f4-2b25d498b603.png)

**Comment by bkw777** [comment]
I don't know what those error messages say.
One guess is if you tried to remove old before rebooting, it can't remove a kernel that you are currently running.

**Comment by bkw777** [comment]
This is normal.
When dpkg installs any package, (a kernel is no different) it creates directories and files. It also keeps track of only exactly the files it supplied, and when it removes a package, it only removes the files it supplied and ignores any other files.
If you add a file to a directory, then when dpkg goes to remove the package, it removes the files it installed, and your added file is still there, and that prevents if from being able to remove the directory.

That all applies to any package, but mostly you don't run into that with most packages. It's common for kernel module packages though, because it's common to build modules for whatever kernel you're running. It can happen automatically via dkms when you install various other packages like video drivers or virtualbox or vmware support packages etc.

Ignore it, or manually delete the indicated directory, or figure out what dkms-using package you have installed and verify that you actually still want it to be building modules for each new kernel you boot. (it could be something you're not even actually using. If you are using whatever module this is intentionally, then this shouldn't have been a mystery)

Look into your dkms config. I think there is a "dkms uninstall ..." command that might be the more correct way to remove the leftover module. Actually I think dkms is supposed to trigger that uninstall command itself when the matching modules package is removed, but it may require the kernel modules package to be built the right way, and maybe the mainline-ppa kernels don't support it. I mostly don't use any dkms modules so I don't really know.

In any event, it's nothing this app controls. We don't create the files that are preventing that directory from being deleted, and so we can't presume to just delete them or the directory. Actually we don't even touch the directory even in the normal case, only dpkg touches anything. And if the kernel packages are missing an uninstall hook to invoke dkms, we don't create the kernel packages.
