### ISSUE TITLE
Please fix the scraping error.

### ISSUE THREAD

**Issue by yanyancyan** [bkw777/mainline#153]
Nice to meet you.
Thanks for providing us with a great tool.

I have found a section that is causing scraping errors that are not your fault.
Could you please take a stab at your tool and fix it?

I am having problems reading versions 5.10.134 through 5.10.140.
The possible causes are as follows
In version 5.10.134 and later, files with "generic-64k_" in the filename have been added.

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/

amd64/linux-headers-5.10.133-0510133-generic_5.10.133-0510133.202207251031_amd64.deb

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.134/

arm64/linux-headers-5.10.134-0510134-generic-64k_5.10.134-0510134.202207291706_arm64.deb

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.140/

arm64/linux-headers-5.10.140-0510140-generic-64k_5.10.140-0510140.202208311247_arm64.deb

I suspect that this file is not reading properly due to it being before the legacy file.

Thanks for taking the time to read this question.

**Comment by bkw777** [comment]
I'm not sure that's the problem.
The "generic-64k" flavors are added, but the "generic" flavor is still there, which is all we look at, just like we don't look at the "lpae" or "lowlatency" or all the other variants that come and go.

The regexes controlling this are:
https://github.com/bkw777/mainline/blob/3c1894452ae8a4024f97b5b0c91ca887f40809b6/src/Common/LinuxKernel.vala#L122

Then later, another regex finds any/all urls in the per-kernel page:
https://github.com/bkw777/mainline/blob/3c1894452ae8a4024f97b5b0c91ca887f40809b6/src/Common/LinuxKernel.vala#L957

and then applies the previous regexes to those results
A version is marked invalid if it is missing a "-generic_" file, for for your arch, for headers or image, or a headers...-all (no -generic_).
(modules are searched and included if present, but not considered invalid if no modules package found because old versions didn't have seperate modules packages)

So, extra files don't matter, all that matters is if the 3 minimum necessary files exist, matching the expected regexes based around "-generic_" and the headers...-all.

It looks like that version actually has all the expected files for amd64:

headers:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/amd64/linux-headers-5.10.133-0510133-generic_5.10.133-0510133.202207251031_amd64.deb

headers...-all:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/amd64/linux-headers-5.10.133-0510133_5.10.133-0510133.202207251031_all.deb

image:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/amd64/linux-modules-5.10.133-0510133-generic_5.10.133-0510133.202207251031_amd64.deb

So it's not a failed build at least for amd64. It is a failed build for other arches but I assume you aren't talking about arm or something.

It does appear to be a regex problem, since, I think those filenames above should match those regexes. But I don't think the mere existence of the the -64k files are causing the problem, since, the "-generic_" files are still there as expected, not replaced by "-generic-64k_".

**Comment by bkw777** [comment]
Structure of the links/filenames didn't change from 132 to 133, yet 133 is marked invalid...
`
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.132/amd64/linux-headers-5.10.132-0510132-generic_5.10.132-0510132.202207212103_amd64.deb
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/amd64/linux-headers-5.10.133-0510133-generic_5.10.133-0510133.202207251031_amd64.deb

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.132/amd64/linux-headers-5.10.132-0510132_5.10.132-0510132.202207212103_all.deb
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/amd64/linux-headers-5.10.133-0510133_5.10.133-0510133.202207251031_all.deb

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.132/amd64/linux-image-unsigned-5.10.132-0510132-generic_5.10.132-0510132.202207212103_amd64.deb
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.133/amd64/linux-image-unsigned-5.10.133-0510133-generic_5.10.133-0510133.202207251031_amd64.deb
`
