### ISSUE TITLE
FIX --install-point offers 6.0.0 when running a 5.x kernel

### ISSUE THREAD

**Issue by allanlaal** [bkw777/mainline#167]
root@S4:/home/allan# mainline --install-point
    mainline 1.0.15
    Distribution: Ubuntu 22.04.1 LTS
    Architecture: amd64
    Running kernel: 5.19.11-051911-generic
    Fetching index from kernel.ubuntu.com...
    OK
    ----------------------------------------------------------------------
    Found installed: 5.19.10-051910.202209221151
    Found installed: 5.19.5-051905.202208291036
    Found installed: 5.19.11-051911.202209231341
    Found installed: 5.17.0-1018.19
    ----------------------------------------------------------------------
    ----------------------------------------------------------------------
    Latest update: 6.0.0
    
    Install Kernel Version 6.0.0 ? (y/n): n
    root@S4:/home/allan# 

Expecting it to offer sth newer than 5.19.11, but still 5.19.x as per mainline `--help`:
`  --install-point     Install latest point update for current series`

**Comment by bkw777** [comment]
What is your show-previous-N-majors setting?

Perhaps it's an interaction with show-previous-N-majors, where, now that at least one valid 6.0 build exists, that is now the current major, and if show-previous-N-majors is 0, then no 5.x are even considered. In that case, this would be expected behavior I think.

But I confess I never use that option. I'll have to look to even see what it claims to do.

In the mean time, try setting show previous N majors to 1 if not already, and then retry.

**Comment by bkw777** [comment]
"--install-point Install latest point update for current series"

"current series" is 6.0

Marking as invalid.

**Comment by allanlaal** [comment]
what about adding a parameter for install-point that would specify (if set) what `major.minor` version I want the point installed to :)
