### ISSUE TITLE
List of available Kernels dramatically curtailed

### ISSUE THREAD

**Issue by jhdore** [bkw777/mainline#171]
I've been using Mainline for the last couploe of months to keep the 5.15 kernel on the latest release for my Kubuntu laptop. It worked very well until recently, but now all it shows is the currently-installed Ubuntu provided kernel and 6.0.0 and 6.0.1. When I reboot I get a message from Mainline that kernel 5.15.70 is available (I was running 5.15.68) but I don't have any other choices in the list to install. 

After upgrade this morning to Kubuntu 22.10 Mainline's behaviour is unchanged, although it now only shows me the currently-installed Ubuntu release 5.19.0.21.21, along with 6.0.0 and 6.0.1. but it did tell me there was a new version of 5.19 to install after reboot.
![Screenshot_20221021_111943](https://user-images.githubusercontent.com/4834815/197178262-c01b97b5-59de-4b9d-aa00-69f046220fd3.png)

I used to have many entries for each version of the Kernel, but they are not showing. I have toggled the 'Hide Unstable and RC releases' setting in the settings, but that only shows me unstable and RC's for 6.x, no 5.x versions - 
![Screenshot_20221021_114449](https://user-images.githubusercontent.com/4834815/197178324-05cfdf7a-0d51-4e47-9c08-6cdbcc2985ba.png)

Is there a file I need to clear out manually, or something? 

Cheers,
James

**Comment by clayg** [comment]
This is speculation, but I'd guess it's because 6.0 came out?  Maybe available is always limited to "the last major version" and that's normally fine except when there's a major versoin bump.  I need those old kernels and don't know how to install them w/o mainline :rofl:

**Comment by clayg** [comment]
It's always like this for me.  So after a bit of greps on the source and an strace, I found `/root/.config/mainline/config.json`

I edied `"show_prev_majors" : "0"` to a `"1"` and reloaded the GUI to see all the old 5.X kernels :+1: 

But then I'm thinking: "well, is this just a doc bug or maybe it's a bug in `src/Gtk/SettingsDialog.vala`" but... no... when I go back to the settings menu... it's right there:

![image](https://user-images.githubusercontent.com/148994/197223117-351c6a48-5694-408b-885d-b560788c1a68.png)

`Show N previous major versions: `

... I don't know why I missed it.  :sweat:

**Comment by bkw777** [comment]
Maybe the default should be 1 instead of 0. It just makes startup so slow re-scanning all those versions every startup. With 1, it means you never have less than one entire major version worth of kernels in cache to re-scan on every startup, and towards the end of each generation it's 2 full major versions. That's a lot.

There are probably several different ways to make a better ui for this.
Maybe build the internal list of every version from the entire main index.html and use that to display at least a greyed-out placeholder entry for all kernels, don't do much processing on most of them, with the listbox showing just a subset with "load more" when you scroll to the bottom etc just to keep it responsive. Then some kind of toggle or right-click option to activate or install one of the "hidden" entries.

And/or, have the roll-off maintain the last N versions at all, any major,minor,point,build, just show say the last 20 kernels whatever they are.

But I think the original point of hinging on the major version was so that you could keep both the most recent major, and the most recent previous major. I think that is a common and useful usage pattern, and keeping an arbitrary number of absolute kernels regardless of version would break that.

**Comment by clayg** [comment]
I wouldn't rush to change anything - I'm an inexperienced user of this tool.  Possibly even go ahead and close this bug, because finding it while in the process of looking for docs was probably partly contributed to my confirmation bias.  I imagine when I glanced at settings originally I might have missed the option because i was expecting a checkbox and not an integer - even when I changed 0/1 I thought I was toggling a boolean!

Thanks for sharing your hard work and engaging with users!

**Comment by bkw777** [comment]
Maybe the label in settings should say some version of "how many" instead of "N". I couldn't really figure out a label that was both accurate and short that didn't also end up being a bit cryptic.

Maybe a cheap answer in the short term is just put a little static label under the listbox that says "To see more or fewer versions, increase or decrease 'Show N majors' in Settings. Failed/incomplete builds are not shown."

Crude but functional.

**Comment by jhdore** [comment]
> 

Ehrmagerd yes - I will don the Cone of Shame for missing that!! I set that to 1 and I can see all the 5.x releases again. Ignore me I must have had a Friday moment...
