### ISSUE TITLE
ubuntu 22.10 1.1.7 from apt package -- segfault

### ISSUE THREAD

**Issue by TimoGoetze** [bkw777/mainline#209]
It worked before. 

Suddenly the UI shows only the installe kernels, and a dialog comes up showing "cant reach"

when using cli:

mainline --debug --list
mainline 1.1.7

(process:64308): GLib-CRITICAL **: 13:44:43.094: g_str_has_suffix: assertion 'str != NULL' failed
Distribution: Ubuntu 22.10
Architecture: amd64
Running kernel: 6.1.13-060113-generic
Speicherzugriffsfehler (Speicherabzug geschrieben)

I did not change anything.. Anyone any Idea - already purged and reinstalled but still same behaviour.

Thanks!

**Comment by TimoGoetze** [comment]
strange.. apt list | grep mainline says:
mainline/kinetic,now 1.1.6-0~202303141447~ubuntu22.10.1 amd64  [installiert]

**Comment by TimoGoetze** [comment]
apt-cache showpkg mainline
Package: mainline
Versions: 
1.1.6-0~202303141447~ubuntu22.10.1 (/var/lib/apt/lists/ppa.launchpadcontent.net_cappelikan_ppa_ubuntu_dists_kinetic_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ppa.launchpadcontent.net_cappelikan_ppa_ubuntu_dists_kinetic_main_binary-amd64_Packages
                  MD5: 658098282b869ca35dbba1e08612eec0
 Description Language: en
                 File: /var/lib/apt/lists/ppa.launchpadcontent.net_cappelikan_ppa_ubuntu_dists_kinetic_main_i18n_Translation-en
                  MD5: 658098282b869ca35dbba1e08612eec0


Reverse Depends: 
Dependencies: 
1.1.6-0~202303141447~ubuntu22.10.1 - libc6 (2 2.34) libgdk-pixbuf-2.0-0 (2 2.22.0) libgee-0.8-2 (2 0.8.3) libglib2.0-0 (2 2.37.3) libgtk-3-0 (2 3.16.2) libjson-glib-1.0-0 (2 1.5.2) libvte-2.91-0 (0 (null)) libx11-6 (0 (null)) aria2 (0 (null)) lsb-release (0 (null)) 
Provides: 
1.1.6-0~202303141447~ubuntu22.10.1 - 
Reverse Provides:

**Comment by TimoGoetze** [comment]
Thanks. updating again worked. I updated already before filing this issue. no idea what was in between. Thanks anyways.

**Comment by bkw777** [comment]
I don't understand, you have 1.1.7 or 1.1.6? How does apt say 1.1.6 while the binary says 1.1.7? I would ```apt remove mainline``` and then make sure it's really gone by ```which mainline``` and ```which mainline-gtk```, then ```apt update && apt upgrade && apt install mainline``` to establish a clean install for sure, and then see if it fails still.

I'm not running 22.10 yet so it's possible something is broken for 22.10 yet not broken for me.

If it still fails after all of the above, please try a new debugging option that isn't really described yet except in the changelog, but it's in 1.1.7.
There is now an environment variable VERBOSE which takes a value from 0 and up which replaces --debug. (--debug still exists, but now it's just a shorthand for VERBOSE=2)
0 = silence all output  
1 = normal output  
2 = --debug  
3 = more verbose  
4 = even more  
5 = really only useful in concert with making code changes to uncomment things and recompiling
So you could do
```$ VERBOSE=3 mainline```
or  
```$ VERBOSE=4 mainline```

And paste the entire results here, or attach as a file.

I would also be curious what happens if you try mainline-gtk and then open & close the settings dialog and then exit, and if that worked, does mainline cli still segfault after that? or if you can't do that, what is the current contents of ~/config/mainline/config.json ?

**Comment by bkw777** [comment]
Hah... well never mind then!

**Comment by TimoGoetze** [comment]
apt package said, 1.1.6 and binary said 1.1.7. But I installed it once a lot months ago -dont know which version that was - and never looked at the cli until gui stopped working few days ago - around the time of your 1.1.7 release. My distro is standard ubuntu 22.10 and regulary updated. no idea what was the cause for this hickup.. 

I cant reproduce the segfault any more. I manually apt updated and upgraded and afterwards package said 1.1.7:
apt list | grep mainline:
mainline/kinetic,now 1.1.7-0~202303160528~ubuntu22.10.1 amd64  [installiert]

**Comment by TimoGoetze** [comment]
even more strange. this morning -gtk crashes again.. hmm with verbose=4 output is
(mainline-gtk:236686): GLib-CRITICAL **: 08:47:07.717: g_str_has_suffix: assertion 'str != NULL' failed
236686: Loaded config file: /home/timo/.config/mainline/config.json
236686: LinuxKernel(,false)
236686: check_distribution()
236686: Distribution: Ubuntu 22.10
236686: check_package_architecture()
236686: Architektur: amd64
236686: check_running_kernel()
236686: Running kernel: 6.1.13-060113-generic
236686: update_cache()
236686: try_ppa()
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by TimoGoetze** [comment]
[_usr_bin_mainline.1000.zip](https://github.com/bkw777/mainline/files/10999116/_usr_bin_mainline.1000.zip)
one apport i could save

**Comment by bkw777** [comment]
thanks much I'll check it out.
I'm away from home for the day.

**Comment by bkw777** [comment]
g_str_has_suffix: assertion 'str != NULL' failed/
plus ending during try_ppa() tells me something already, thanks for the debug

that tells

**Comment by jdenekat** [comment]
I am seeing the same thing on linux mint 21.1.  Two days ago was seeing "can't reach", but am now getting the g_str_has_suffix assertion.
mainline/jammy,now 1.1.7-0~202303162031~ubuntu22.04.1 amd64 [installed]

**Comment by bkw777** [comment]
Nothing like pushing a barely tested update and then being unavailable to fix it for 2 days...

**Comment by jdenekat** [comment]
Wasn't actually complaining, just trying to provide more information.  Love the tool.  Look forward to being able to use it again.

**Comment by bkw777** [comment]
Ok I just pushed a small update that makes load_app_config() more resislient.

**Comment by pavkriz** [comment]
On version 1.1.8, Ubuntu 22.04.2, I had to delete ~/.config/mainline to make it run.

**Comment by bkw777** [comment]
After updating to 1.1.8 could someone with the problem please paste the output of :
```
$ ls -l ~/.config/mainline
$ cat ~/.config/mainline/config.json
$ VERBOSE=4 mainline --list
```
The way the config loader is written now, it shouldn't matter *what* the file contains, missing options, malformed json, etc. I can't make it fail on my machine any more no matter what I do to it. Maybe there is some permission problem from running with sudo some time in the past, or maybe one thing I'm not handling well enough yet is when an expected option exists and loads fine, but contains a bad value? Or maybe even different versions of valac aren't behaving exactly the same wrt the compiled-in defaults in the global context. Seems unlikely but it must be something obvioiusly.

**Comment by TimoGoetze** [comment]
`
$ ls -l ~/.config/mainline
-rw-rw-r-- 1 user user 381 Mär 16 12:13 config.json
-rw-rw-r-- 1 user user 878 Mär 16 12:13 notify-loop.sh


cat ~/.config/mainline/config.json
{
  "ppa_uri" : null,
  "all_proxy" : null,
  "notify_major" : "false",
  "notify_minor" : "false",
  "hide_unstable" : "false",
  "previous_majors" : "8",
  "notify_interval_unit" : "0",
  "notify_interval_value" : "0",
  "connect_timeout_seconds" : "4",
  "concurrent_downloads" : "3",
  "window_width" : "916",
  "window_height" : "790",
  "window_x" : "0",
  "window_y" : "0"
}

$VERBOSE=4 mainline --listt
523399: mainline 1.1.8
523399: load_app_config()
523399: json_get_string(ppa_uri,https://kernel.ubuntu.com/~kernel-ppa/mainline/)
523399: json_get_string(all_proxy,)
523399: json_get_bool(notify_major,false)
523399: json_get_bool(notify_minor,false)
523399: json_get_int(notify_interval_unit,0)
523399: json_get_int(notify_interval_value,4)
523399: json_get_int(connect_timeout_seconds,15)
523399: json_get_int(concurrent_downloads,1)
523399: json_get_bool(hide_unstable,true)
523399: json_get_int(previous_majors,0)
523399: json_get_int(window_width,800)
523399: json_get_int(window_height,600)
523399: json_get_int(window_x,-1)
523399: json_get_int(window_y,-1)
523399: json_get_int(term_width,1100)
523399: Member not found in JSON object: term_width
523399: json_get_int(term_height,600)
523399: Member not found in JSON object: term_height

(process:523399): GLib-CRITICAL **: 08:26:28.054: g_str_has_suffix: assertion 'str != NULL' failed
523399: Loaded config file: /home/timo/.config/mainline/config.json
523399: LinuxKernel(,false)
523399: check_distribution()
523399: Distribution: Ubuntu 22.10
523399: check_package_architecture()
523399: Architecture: amd64
523399: check_running_kernel()
523399: Running kernel: 6.1.13-060113-generic
523399: LinuxKernel.query()
523399: query_thread()
523399: download_index()
523399: try_ppa()
Speicherzugriffsfehler (Speicherabzug geschrieben)


`

**Comment by TimoGoetze** [comment]
i confirm that its running again after removing old config.

**Comment by bkw777** [comment]
Thank you for the config.json
I think I see what happened now.

First ```has_suffix``` is only used on ppa_uri to append a "/" if it's not there already, in case a user manually edits the url, (the whole point of moving the url into the config file is to make that possible, even though it's not exposed in the settings screen)

And ```"ppa_uri":null,``` is something I didn't account for. It's neither malformed json nor simply entirely absent.

And I think how it ever got there is by one of the many recent short-lived versions. That field is only a few weeks old, and there were a few versions recently where it was broken without me realizing it because I had a good config file and I didn't test what happens on a fresh install or on update from a valid old config file.

And *now* I didn't test well enough when you get a config file generated by one of those bad versions.

And the fix is once again to just get rid of some TeeJee code that never needed to exist in the first place. The config  loader is using some small helper/wrapper functions in TeeJee.JsonHelper.vala, but all they do is essentially the same thing as some functions that are provided by the Json library.

IE, TeeJee.JsonHelper.vala has json_get_string(field_name,default_value) which attempts to return the requested value, or the supplied default value, so that either way you can use the return value without worrying about it. Except it doesn't handle the null case, only the not-found case. It would be simple to fix that, but even better is the entire function never even needed to exist in the first place because the Json library provides get_string_member_with_default(), which does the same job and *does* handle the null case.

**Comment by bkw777** [comment]
1.1.9 reworks the config file and built-in defaults significantly. Hopefully more solid now.
