### ISSUE TITLE
"Uninstall Old" uninstalls newly installed newer versions.

### ISSUE THREAD

**Issue by ibrahimBeladi** [bkw777/mainline#213]
I had several old versions and installed a new one. After the installing was complete, I used the Uninstall Old option, and it removed the newly installed version.

I think it just removes everything that is not in "Running" status.

**Comment by bkw777** [comment]
There was a recent change to the uninstall-old logic. I think what you're seeing is intended, but you'll have to say if this actually matches what you saw:

Previously the behavior was it uninstalled anything older than the currently running version.
That was always kind of wrong, since the only thing special about the currently running version is that you can't uninstall it while you're currently still booted on it. Other than that, it's just a version like any other, and there is no special reason to use it as a newer/older threshold.

Now the button actually does what it says. It uninstalls everything older than the latest installed one, with the only exception being that if you haven't rebooted yet, then it has to skip over the currently running version.

So, if you are currently running 6.2.6, and have 6.0.9 installed from before, and just now installed 6.2.7 and 6.2.8
And then hit uninstall-old before rebooting, it will uninstall 6.2.7 and 6.0.9  
It keeps 6.2.8 since it's the highest installed version.
It uninstalles 6.2.7 because it is older than the latest installed one.
It keeps 6.2.6 because you are currently running on it and it has no choice but to keep it.
It uninstalls 6.0.9 because it's older than the latest installed one.

If you reboot to 6.2.8 first and then uninstall-old, it will uninstall everything older than 6.2.8

The fact that you may have only just now installed 6.2.7 and it's newer than what you're currently running doesn't really matter. It's still older than the latest installed. If you want multiple versions installed instead of only the latest one, then don't hit the button that says "uninstall everything older than the latest installed one"

However, there is a feature request in another issue to add whitelist/blacklist tags to the kernel list so that you could tag a kernel to be protected (never remove) or excluded (ignore) or taboo'd (never install) etc. I will probably add that sometime soon. Lately I have been more active and that is a nice not-too-difficult feature to add.

**Comment by ibrahimBeladi** [comment]
If I recall correctly, I installed only 1 version apart from my current running version. And it was removed along older versions.

For example:
- I have 6.2.6 installed, with 2 older versions, say 6.2.5 and 6.2.4
- I installed 6.2.8 without rebooting (6.2.6 is still active)
-  I clicked uninstall old, it did remove everything including 6.2.8 despite being after 6.2.6

**Comment by bkw777** [comment]
That would definitely be unintended and borken. I have another update pending, and I've been testing that funcionality as part of it, so perhaps this next update fixes it. I mean it's been working as expected for me so it should for you.

**Comment by bkw777** [comment]
Ok I just pushed a preliminary 1.1.9

**Comment by bkw777** [comment]
I think this doesn't happen now.
