### ISSUE TITLE
1.1.9 installing 6.2.8 fails with assertion failed

### ISSUE THREAD

**Issue by SamuelMarks** [bkw777/mainline#215]
![image](https://user-images.githubusercontent.com/807580/229325640-9e6b7e13-509e-4a30-b7a3-891a543b7a2b.png)

(was trying to resize the window for this issue but that screwed up as you can see)

**Comment by bkw777** [comment]
I know what it is. fix shortly.
Simple fix but in the meantime, workaround you could do right now now is in settings, enable Verify Checksums.

It's off by default because it's new and adds complication, but it will cause the field that's currently getting a null to be filled and allow the rest of the process to work.

**Comment by garak** [comment]
I tried the proposed workaround: the kernel is installed, but then it fails at boot with "bad shim signature. You need to load the kernel first"

**Comment by bkw777** [comment]
That's not the app, that's because you have secure-boot enabled in your bios, and the mainline-ppa kernels are unsigned.

This is not anything the app causes or has any control over.
IE: if you manually download the same .deb files, dpkg -i foo.deb, reboot, the same thing would happen.

You have 3 options:
* disable secure-boot in your bios
* try to figure out https://github.com/M-P-P-C/Signing-an-Ubuntu-Kernel-for-Secure-Boot
* don't use unsigned kernels (all mainline-ppa are unsigned)
* 4th out of 3 :) maybe there is some shim bootloader where the bootloader is signed and satisfies the bios, yet is willing to boot an unsigned kernel. I have no idea I'm just saying in theory for completeness.

In reality it's really 2 choices: disable secure-boot or don't use mainline-ppa kernels.

**Comment by SamuelMarks** [comment]
Thanks @bkw777 that did the trick. Oh but I lost the "CHANGES" button, I liked that feature!

**Comment by bkw777** [comment]
PPA button

**Comment by bkw777** [comment]
https://github.com/bkw777/mainline/discussions/224
