### ISSUE TITLE
mainline-daily in bionic: Failed to build

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#226]
dh: Sorry, but 12 is the highest compatibility level supported by this debhelper.
debian/rules:20: recipe for target 'clean' failed
make: *** [clean] Error 255
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=chroot --series=bionic --arch=amd64 RECIPEBRANCHBUILD-3523861
Scanning for processes to kill in build RECIPEBRANCHBUILD-3523861

https://launchpadlibrarian.net/660508237/buildlog.txt.gz

**Comment by bkw777** [comment]
ok I just changed it to 12

**Comment by bkw777** [comment]
looks like it's been failing on bionic since 1.1.8 for a totally different reason
`Json.Object.get_string_member_with_default' is not available in json-glib-1.0 1.4.2`
So it looks like in order to support bionic I'll have to put some form of wrapper functions for the simpler no-default json functions back in like the TJ ones I took out recently. blech.

**Comment by bkw777** [comment]
bionic should be working again with 930a9d8
