### ISSUE TITLE
[Feature/Idea] Update software name for recognition

### ISSUE THREAD

**Issue by Seltonu** [bkw777/mainline#23]
It'd be a good idea to give Mainline a more unique name. This will allow users to better reference it outside of the project (such as the well known "UKUU" it's forked from).

A more unique name will bring more users, and hopefully more contributors.

5 second ideas:
-KernelPop? (like popcorn)
-UMKU: Ubuntu Mainline Kernel Updater
-FUKUU: Forked Ubuntu Kernel Update Utility

**Comment by eitch** [comment]
I find mainline quite alright, but it's true that does not say much about the project. I do like KernelPop though: always popping that latest kernel on to your machine...

**Comment by bkw777** [comment]
I definitely like fukuu. omg that is, delightfully perfect. But I only want to be that childish on the inside, not on the outside. :) Plus I don't *actually* hate TeeJee quite that much.

It's "mainline" because shortness and simplicity is better than expressiveness in a name. WTF does "verizon" mean?

I'll say KernelPop is just not my style by a mile. "umku" I find awkward and klunky, and I felt exactly the same about "ukuu", but it is both short and distinct which is good in a name. I know you said those were only 5-second thoughts, so take those more about showing what I'm thinking about names in general, not about shooting down your ideas.

I'm open to ideas, but I did put more than 5 seconds thought into the name, so it may just take a little more than that that's all.

That's assuming there is even any problem that needs fixing. What do we care how many other people discover or use this? And does some other name actually change that anyway?

Maybe a good enough one does, and there's know way to say until it gets dreamed up and spoken, so that's why I say I am actually open to hearing the ideas, even if in the end I hear 20 ideas and don't like any of them, so what? Let'r rip anyway. Maybe everyone else will love one so much you all convince me about it even if I didn't like it at first.

And no real hurry either. This issue can stay open forever for all I care. Let it sit there in the back of our heads for a while and maybe something cool will come up.

**Comment by ObeseChicken** [comment]
it says ukuu notification under the startup entries in mate... btw i vote fukuu

**Comment by bkw777** [comment]
Nothing says ukuu anywhere except comments and credits. Mate must be using something else.

**Comment by noah1510** [comment]
I would also vote for fukuu or ukuu++ (or something similar)

I also find it really hard to find, most of the time I go to ukuu and look through all the forks to find this repository since ddg and the github search show so many other tings that are named mainline that you have to know where to find it to actually find it.
So I really think it would make it a lot easier to find this project.
It is not only about new people finding this repository this really should also be about people using the project finding it.

> What do we care how many other people discover or use this?

At the moment, most of the time when someone looks for a tool to update their linux kernel (on ubuntu based distros) the most popular answer is 'just use ukuu' which you have to pay for or use an unmaintained version.
Most people will then use it instead of looking through the forks to find one that is maintained.
Mainline is a tool which makes the linux desktop experience way better especially for newer hardware, which is why I usually recommend it (and I think distros should start using it as their default kernel manager) but for people new to linux/github/foss it is really too hard to find even if they would actually need it.
