### ISSUE TITLE
No kernels available except for installed ones

### ISSUE THREAD

**Issue by JustMaris** [bkw777/mainline#233]
On the day when the release of kernel 6.3 was announced, I checked mainline and I saw that I couldn't install any kernels. The only ones that were shown were the ones that were already installed.
I remember that sometimes it takes time for things to change with availability, so I waited, but still, nothing changed.
What is the issue and is there anything I'm doing wrong? I tried --clean-cache command, but it didn't make a difference.
This is what I'm currently seeing when I open UI:
![image](https://user-images.githubusercontent.com/24903212/235760267-e46e95c4-89dd-44d6-a77e-3e3ead74521f.png)

Edit: Added image.

**Comment by bkw777** [comment]
The Reload button now deletes the cache so you don't really need --clean-cache any more except for non-gui use.

Can you run `VERBOSE=4 mainline-gtk` and past the output?

**Comment by bkw777** [comment]
Also are you using 1.2.5?

**Comment by JustMaris** [comment]
This is the output and yes, I'm running 1.2.5.

Just tried to run mainline-gtk with sudo and it showed all kernels after 6.2.9 up to 6.3.1

**Comment by bkw777** [comment]
You have a problem right when it tried to download the main index. Perhaps you previously ran as root and the cache directory or some files within it got created by root, and now the user doesn't have permission to delete or overwrite?

In your debug output starting at the 2nd aria2c command, that is where it downloads the main index.html to a temp file and then if the download was successful renames it from the temp name to index.html, unless the download failed or some other problem, so that in the end if the new file wasn't retrieved, at least you still have the old one (if there was one)
it should look like this:

787853: AsyncTask begin()
787853: working_dir: '/tmp/.mainline.O1CM9jsR'
787853: dir_delete(/tmp/.mainline.O1CM9jsR)
787853: _dir_delete(/tmp/.mainline.O1CM9jsR)
787853: file_move('/home/bkw/.cache/mainline/Af2WPhnJ','/home/bkw/.cache/mainline/index.html')
787853: dir_create(/home/bkw/.cache/mainline)
787853: file_delete(/home/bkw/.cache/mainline/index.html)
787853: OK
787853: load_index()
787853: file_read(/home/bkw/.cache/mainline/index.html)
787853: LinuxKernel(v2.6.27.60/,true)
787853: kernel_list.add(v2.6.27.60)
787853: LinuxKernel(v2.6.27.61/,true)
787853: kernel_list.add(v2.6.27.61)
787853: LinuxKernel(v2.6.27.62/,true)
787853: kernel_list.add(v2.6.27.62)

Where you have:
170767: _dir_delete(/tmp/.mainline.FfAazc0p)
170767: load_index()

In betwee those two line should be
787853: _dir_delete(/tmp/.mainline.O1CM9jsR)
787853: file_move('/home/bkw/.cache/mainline/Af2WPhnJ','/home/bkw/.cache/mainline/index.html')
787853: dir_create(/home/bkw/.cache/mainline)
787853: file_delete(/home/bkw/.cache/mainline/index.html)
787853: OK
787853: load_index()

So you never got the index.html, and so load_index() has nothing to work on.

I would try manually `sudo rm -rf .cache/mainline`
And then don't ever run mainline with sudo. You can run it as root if you're logged in as root, but not sudo.

Also double-check the ownership and permissions of the parent .cache dir too just to be thorough
$ ls -la ~ |grep cache
drwxrwxr-x  83 bkw  bkw     4096 May  3 18:41 .cache

**Comment by bkw777** [comment]
And I think we just found a new bug of some sort...
On my own system, I did NOT see 6.3.1 until after I hit Reload. Merely starting the app did not show i, even with several open/close/open. I also did not get any notification about 6.3.1 though that might have been normal for my 4 update check interval.

**Comment by bkw777** [comment]
... and I just tried to mock up the prior state by deleting just the 6.3.1 directory from the cache, and deleting the 6.3.1 line from the cached index.html, started the app, ... and it worked normally.
6.3.1 showed up. I guess I can't replicate the bug. I'll keep trying, and we'll see what happens for 6.3.2 I guess.
But I definitely remember that 6.3.1 was not showing for me, and it's apparently been up for 3 days by now.

**Comment by bkw777** [comment]
assuming it was a root file permissions issue, feel free to re-open if you have more to report
