### ISSUE TITLE
Stuck in Kernel V6.4.3

### ISSUE THREAD

**Issue by abdelouahabb** [bkw777/mainline#283]
Hi,
`sudo mainline --install-latest` thinks that only `6.4.3` is the latest, (event forcing the version does not find any prior version), cleaning the cache does not solve the issue

**Comment by abdelouahabb** [comment]
> Works for me. Do you by chance have a 6.5-rcN installed? I just noticed that if you un-hide unstable in settings, install say 6.5-rc3, then hide unstable in settings, it sees that installed 6.5 as greater than 6.4.x and so if you only had say 6.4.3 installed it ignores 6.4.6. I should make it handle that case differently so that if unstable is currently hidden, then don't count any unstable when scanning all installed kernels to determine the highest installed vs the highest available. But that still only affects --install-latest, --install-point, and --notify. You can (well, I can anyway) still install 6.4.6 by selecting it in the gui or by `mainline --install 6.4.6`
> 
> You can try `mainline --list -v 3` and paste the output.
> 
> It's slightly recommended not to run with sudo. You can, it all still works, it's just that it does the downloads and caching as root also which isn't needed. If you run it without sudo, it will invoke pkexec or sudo or whatever you want just when it needs to for dpkg and everything else happens as the user.

Thank you for the hint,
I never install an rc ,
BTW, it worked today with `v6.4.6`, that's weird, maybe the 3 other version were not formatted in the same way to be parsed in the list ?

**Comment by bkw777** [comment]
More likely it just wasn't a valid kernel at that time. (failed or incomplete build)
They often post kernels that aren't valid at first, then get updated and become valid later.
In that case it was normal and correct that you couldn't install it.
After the fact there is no way to show it since the web site only shows it's current state, not any past states.

If you want, there is a config option now to show the invalid versions instead of hiding them. That way you can see right in the gui or in the `--list` output why you can't install some version. It will actually say "6.4.3 Invalid"
For instance, 6.4.4 and 6.4.5 weren't posted for several days after they were available upstream, and now they are posted but invalid (failed builds), and 6.4.6 is the first valid build since 6.4.3. 6.4.4 and 6.4.5 would normally not be shown in the list at all, but you can un-hide invalid in settings and see them.

Except, I never had any problem with 6.4.3, it installed fine as soon as it showed up, so I don't think 6.4.3 was one of those.
So maybe you just had some transient network issue. Or maybe 6.4.3 was one of those and you just happened to catch it early and by the time I tried to install it was updated and good by then.

To check for network problems (next time it happens) you can just try hitting the PPA button to see if you can even reach the server and download the same deb files in a browser right at the same time. Or run `mainline-gtk -v 3` and the verbose output should show if there is a problem downloading or or some other problem like directory permissions etc.

Anyway, it actually sounds like a normal transient thing all in all. Normal meaning nothing the app can do. Either the build was not valid right at the time you tried, even though it is now, or the site wasn't reachable right then because of either network issues or load on the server from other downloaders. Both of those things happen all the time.
In any case, always just try running with `-v 3` or higher and paste the output if it doesn't tell you anything yourself.
