### ISSUE TITLE
fix uk.po

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#29]
[uk.zip](https://github.com/bkw777/mainline/files/4606777/uk.zip)

**Comment by bkw777** [comment]
Take a fresh look. This is probably already slightly obsolete. I have been making a lot of changes this weekend fixing up the thrice-damned temp files and adding a sweet new notification system. There are a few new localizable strings in the notifications and a couple other places.

It would be a lot more convenient if you coud use git and do a pull request.

**Comment by cappelikan** [comment]
i.e. take message.pot ?

пн, 11 трав. 2020 о 05:12 Brian K. White <notifications@github.com> пише:

**Comment by cappelikan** [comment]
I send renew translate uk.po

пн, 11 трав. 2020 о 05:53 Sergiy Golovko <cappelikan@gmail.com> пише:

**Comment by bkw777** [comment]
No you edit uk.po like you have been.

messages.pot is automatically generated from all the source files. You don't edit that because it will just get overwritten.

And since I did some work in Makefile recently, And every time I run "make", all the *.po files are also automatically kept in sync with the new messages.pot, and so, automatically kept in sync with the current source. Obsolete strings (strings that no longer exist in the source) are removed, new strings that appeared new in the source are added (usually with no translation), and all the line numbers get updated, while preserving all the translations.

Now, every time a string is added or removed in one of the source files, that string will appear or be removed from all the *.po files. It all happens every time anyone runs "make" so it's just always being kept in sync now.

So all you need to do is look over uk.po in any plain text editor and and fill in the missing translations or improve the bad ones etc, then pull-request that po file back to me.

Since the file is a simple format and the edits are limited, you can actually just do it right in the github web site. You can fork, edit, and PR back all right in the browser in a few minutes.

**Comment by cappelikan** [comment]
I understood all the edits via the web to uk.po made

пн, 11 трав. 2020 о 12:55 Brian K. White <notifications@github.com> пише:

**Comment by cappelikan** [comment]
Well very thanks

пн, 11 трав. 2020 о 18:57 Brian K. White <notifications@github.com> пише:
