### ISSUE TITLE
Application restarts required to uninstall multiple kernels

### ISSUE THREAD

**Issue by joooeey** [bkw777/mainline#293]
## Issue

After uninstalling one kernel, I can't uninstall another one without restarting mainline. It took me many hours to find out that this is the issue. I don't remember the exact error message I got when trying to uninstall a second kernel with the "Uninstall" button but it contained the text `uninstalling selected kernels:` and `no uninstallable packages found` (with some uppercase letters).

The same thing happens after I try to uninstall one kernel but it fails due to dependency problems. Then I can't uninstall any other kernel without restarting mainline.

## Software Versions

* Mainline Kernels by Brian K. White: 1.4.0
* Ubuntu 20.04.6

**Comment by bkw777** [comment]
Well I changed a lot of stuff the last few days so I guess I broke something. I'll check it out.

**Comment by bkw777** [comment]
Actually I can't duplicate this error, it's working fine for me.
So could you update to 1.4.3 and try again with `mainline-gtk -v 3` ?

**Comment by joooeey** [comment]
I just tried this on another machine:
- Mainline Kernels 1.4.3
- Linux Mint 20.1

A very similar problem appears. I did the following steps:
1. Install mainline (I didn't have it before.)
2. Start `mainline-gtk -v 3`
3. Install a newer kernel.
4. Install an even newer kernel.
5. Try to uninstall the kernel from step 3. =====> This fails with:
```
Kernel "5.8.18-050818.202011011237" not found
Uninstalling selected kernels:
Uninstall: no uninstallable packages found
mainline: done
```
[mainline_terminal_log.txt](https://github.com/bkw777/mainline/files/12192479/mainline_terminal_log.txt)

**Comment by bkw777** [comment]
I think you have a combination of issues.
You only supplied half of what I asked for, missing the terminal logs from the actual install/uninstall windows, but even from just the log from the parent mainline-gtk process I see something that shouldn't be happening:
```
TerminalWindow execute_cmd(mainline --index-is-fresh --install 6.3.9)

(mainline-gtk:11621): GLib-WARNING **: 10:53:07.539: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
TerminalWindow child_has_exited(0)
```
That error was resolved and removed several versions ago, yet you still got it.
I think it has something to do with the backwards-compatibility code to support older versions of vala and vte. Old and new versions of Vte.Terminal have a different way of monitoring the child process, and maybe I got something wrong with the "fallback to the old way" code.

So I fired up a mint 20.1 vm to build and debug in that environment to clear that up, and mint 20.1 appears to have a broken package repo right out of the box.

On a fresh live boot of the install cd, just `sudo apt install valac` results in a dependency error, without any messing with the apt config or anything yet. It doesn't say there is no valac, it says there is a valac package in the stock default repo, that somehow doesn't have it's dependencies in that same stock default repo.

Then when I tried to run synaptic to explore the dependencies interactively, it produced gtk errors that I don't get on my normal ubuntu/xfce system. That error suggests either synaptic is written wrong (performing actions out of order or race condition etc), or there is some issue with the installed gtk libraries/versions. That error isn't a critical error and synaptic still runs and works, it just exposes that there is a mis-match somewhere.
![Screenshot_mint_20 1_2023-07-28_16:10:23](https://github.com/bkw777/mainline/assets/54458165/51afc8bb-28fb-4b88-a963-4ffa5e02fa02)

These are both glitches in the base system before even touching mainline, so although I'm sure there is some kind of hole to patch in mainline, it also appears that at least some of the problem is due to Mint, or at least this version, being slightly broken.

Mint is debian-based and so mainline should at least nominally work on it (even if the actual kernels aren't usable because they weren't built for anything but ubuntu), and it's popular, so I'm still looking into it and will probably figure out some answer, but for now I'm just relaying what I see initially. It looks like this version of mint, at least out of the box before doing any updates, is possibly simply buggy wrt dependencuy gtk library packages.

**Comment by bkw777** [comment]
After doing a full install instead of just running the live environment, and doing normal updates, there is no more dependency probnlems and it's possible to build, install, run normally at least, but I am definitely reproducing your symptoms.

One thing I see is when I install 5.8.18, it does not recognize 5.8.18 as being a mainline kernel. You see it in the list with the ubuntu logo instead of a tux, and the display version number is the long internal dpkg package version string instead of just "5.8.18" like it should be. That is why it also fails to "find" it when you ask to uninstall it.

However if you hit the Reload button, that forces mainline to delete and rebuild the cache from scratch, which rebuilds kernel_list from scratch too, and after that, 5.8.18 shows up as a mainline kernel like it should, and, is uninstallable just like normal with no weirdness.

I think this may actually be related to that Vte error about watching the child pid when something else is already watching the child pid. The parent mainline-gtk process is supposed to block and wait while the child terminal window is running, but on this system that isn't working for some reason and the parent process starts moving again before the child process is done, and that causes the parent process to get bad or incomplete data when it goes to refresh kernel_list for display in the main gui window.

So I'm poking at it now. It does require debugging actually in this environment since I don't get the same behavior on other systems with the same code. That very first error I mentioned from your log I thought was merely a cosmetic issue that wasn't really the problem but just sort of evidence of something fishy somewhere, but actually it looks like that terminal child pid glitch may actually be the source of the problem.

**Comment by bkw777** [comment]
Hah!, it's definitely the vte sync vs async code.

Try this: go into settings External Commands and select any of the other terminals that you may have installed.
I am testing on mint 20.1 cinnamon so that is gnome, so it has gnome-terminal installed out of the box. If you're using the xfce version, unfortyunately xfce-terminal has a unique problem that no other terminal has. You can't use it for this because it can't be told not to fork and run the -e command... argument in a seperate process. The xfce-terminal process will return instantly even while the real terminal and shell command inside it are still running. So, all of the terminals in that list are tested, so you can use any of them if you install them. For an xfce system I'd suggest install sakura or urxvt to try to stay light like the rest of xfce, select that terminal in settings, and then install/uninstall kernels all you like, and it works correctly.

The problem is that the internal vte terminal is not blocking when the parent process needs it to, and the fault is all in TerminalWindow.vala. The external terminal feature bypasses that and doesn't use TerminalWindow.vala at all. So just using that feature is a cheap immediate way to just avoid hitting the broken fallback-to-older-vte-method code around the internal vte.

You can do this now with your existing install even while I haven't fixed the real problem yet.

**Comment by bkw777** [comment]
It is still doing one thing wrong though, though it's only an annoyance not a breakage. The child mainline proccess is not respecting `--index-is-fresh` and it's downloading the main index for no reason. I'll fix that too of course.

**Comment by joooeey** [comment]
I can confirm the issues I've described above don't occur anymore on Ubuntu 20.04.6 GA with Mainline Kernels 1.4.8 installed via automatic update.
