### ISSUE TITLE
Fix German “translation”.

### ISSUE THREAD

**Issue by navid-zamani** [bkw777/mainline#307]
The German translation seems to be generated by an automated tool, that implies the wrong context.

E.g. the “Lock” column is translated with “Schleuse”. Which is the thing that ships go through. ^^
“Sperre” would probably be correct.  
And “Nachladen” should be ”Neu laden” or “Auffrischen” (refresh).
“Ausgang” should be “Beenden”. 
I don’t know what “Ungültig” is supposed to stand for. Maybe “Funktionsunfähig” was meant. Or “Defekt” (defective). “Invalid” really has no proper direct translation in that context.

The settings also are half-translated.

If you send me a text file or other easy to use thing, I’ll gladly translate it to proper German.
(Germany sadly has a high level of functional analphabetism, caused by badly designed spell checkers and a general misuse of English by lesser educated people. So good translations are hard to come by. About half the products on our supermarket shelves contain grave grammatical errors.)

**Comment by bkw777** [comment]
I don't know what the "right" way is, but you can just edit po/po.de manually easily enough. It should be pretty easy to see what to do when you look at it. You can even do it right here in the github ui.
https://github.com/bkw777/mainline/blob/master/po/de.po

Except for the header at the top, everywhere you see `msgid`, that is an original English string. You write the German version of that after `msgstr`.

The string may be one long string within a single set of quotes, or may be broken into any number of shorter sets of quotes. They all get catted together as if they were one string internally, and the file gets reformatted and re-written during  "make" and ends up with a default line length regardless how you write the strings, so just write however you want.

```
# a comment
msgid  "This is the original text. It was written by %s using %s.\nIt might"
" be split into multiple chunks like this."
msgstr ""
```

You write whatever you want inside the "" after `msgstr`
```
msgstr "this is a set of words"
```
and
```
msgstr "this"
" is "
"a"
" "
"set of words"
```
are both the same.

The proper tools also verify the formatting of the file, but if you just do the above without otherwise altering the format (like, don't try to add or remove mgsid or msgstr lines, just edit the arguments to existing ones, don't write outside of quotes, preserve any %s or other printf format codes, etc, then you should be fine. Worst case I can just fix it easy. I'd rather have the translation so don't worry about breaking the file.

The file ends up getting reformatted anyway by one of the gettext utils during "make", so  it doesn't matter where you break up long strings. It will get rewritten with some default line length.

Also edit the Last-Translator field in the header to put yourself. You can write pretty much whatever you want in there if you don't want to write a valid email.
