### ISSUE TITLE
feature request: update linux-firmware

### ISSUE THREAD

**Issue by VladimirMrzv** [bkw777/mainline#335]
Also with update kernel some devices need update firmware. On Ubuntu LTS builds did not updates and must update it manual.

I was got problem with new mesa and new kernel, my issue
https://gitlab.freedesktop.org/mesa/mesa/-/issues/10793

Maybe add function to update to latest package of firmware

**Comment by bkw777** [comment]
As far as I can tell this is out of scope.  

kernel.ubuntu.com does not produce any package named "linux-firmware", and the kernel packages don't declare any dependency on such a package either.

If the mainline-ppa site produced a firmware package, we could include it and install it like the rest, but they don't.

If the kernel packages declared a dependency on a firmware package that the system was supposed to provide (like they do for libc, libssl, etc) then we could maybe run a dpkg info command to detect that requirement and maybe try an update, but they don't.

I'm not willing to try to touch any other packages than the supplied packages themselves or *maybe* explicitly declared dependencies, because that would be unexpected and break some people.

Please see the faq section of the readme:
https://github.com/bkw777/mainline?tab=readme-ov-file#help--faq
Including the first big link to the [MainlineBuilds wiki](https://wiki.ubuntu.com/Kernel/MainlineBuilds)

If there is something you still think should and could be done, please explain it in more detail. Maybe a config option for user-specified extra commands or something?

**Comment by theofficialgman** [comment]
Bump on this. Having a way to install newer linux-firmware is needed to actually make use of many new features and hardware support in newer linux kernel versions. I am aware that upstream canonical doesn't do this but you should try and get the parties involved in making the mainline kernels to produce such packages.
