### ISSUE TITLE
Feature request: Add a column with the release date of the kernel version

### ISSUE THREAD

**Issue by flip111** [bkw777/mainline#337]

**Comment by bkw777** [comment]
I think this would have to be first a feature to enable/disable columns in general, and this could then be a column that's disabled by default but available.

I don't want any more clutter but it might be useful to be able to sort by date since frequently multiple major versions get updates at the same time, and the highest version number is not always the most recent update.

But mostly I don't think most people care about the release date enough to be worth adding more text to the screen.
What I mean by not caring is, what does it change about your life as a typical user looking to stay current? I think most people only want to know they have whatever is the latest available. I know I never care about the date, but if I ever did, it's visible in the filenames in the tooltip when hovering over a row, and it's also available by clicking the PPA button. I never need to see all the dates at a glance to scan them for some reason.

I'm sure you have your reason of course but it feels like a niche need.

**Comment by flip111** [comment]
Didn't know i could hover and see the date. It's sufficient for me
