### ISSUE TITLE
Idea and proposal to avoid problems with updating kernels

### ISSUE THREAD

**Issue by cappelikan** [bkw777/mainline#342]
There is a proposal to introduce an option to hide / open entries in the list of kernels , people began to mistakenly delete this entry and then became indignant about why the kernel was not updated. I would like to have the option in the settings of something like expert or normal mode, in expert mode we set rules with checkboxes, for example, whether to hide certain items or not, but in normal mode everything remains as is. Thanks
![Знімок_20240808_061210](https://github.com/user-attachments/assets/2501ee4a-d80c-4e35-957f-619f60072d2b)

**Comment by bkw777** [comment]
Meh. I don't think this app has enough settings in total to warrant a reduced subset for complexity/confusion reasons.
A "restore defaults" button might not be a bad ideea though to reset things that could really break it like the ppa url, terminal, and sudo options etc.

You would have to define what the "normal mode" should do, and explain the reasoning, and show that 1/2 of users wouldn't think that "normal" shouldn't be the opposite of whatever you think "normal" should be.

For instance, should "normal" show all kernels, or only the generic ones?
Should normal show broken not-installable versions or not?
There is no answer to either of those because there are totally valid arguments both ways, and people who think each way is obviously crazy.

Which means there is no such thing as "normal", there is only my preference and your preferrence, and the users preferrence.

So I can't decide for anyone else except for picking the default.
