### ISSUE TITLE
What is Purge?

### ISSUE THREAD

**Issue by VincentJoshuaET** [bkw777/mainline#40]
I just installed the app, I see that the Purge button is clickable already, yet Remove is not.

**Comment by bkw777** [comment]
I guess this should get a tooltip or something because you're right it's not obvious.

It's a one-button to automatically remove all kernels older than the newest one installed, although not including the currently running one if you just installed a new one and haven't yet rebooted into it. I never use it myself but it was in the app originally and it seems like a handy thing that other people probably use.
