### ISSUE TITLE
[Feature Request] Option to select default kernel to boot with

### ISSUE THREAD

**Issue by Seltonu** [bkw777/mainline#42]
Would be really helpful to have an option for selecting the kernel you want to boot with. I fairly often need to jump between kernel versions for software compatibility, but there's no way I know of to select one persistently. Not sure how difficult this would be to implement.

Right now, when I'm booting Pop!_OS it's either boot normally and run the most up-to-date kernel currently installed, or run "old kernel" which the behaviour is inconsistent and requires selecting this at every boot. 

I also often have to purge all old kernels to be able to get the one I want to boot (i.e. if running 5.7 but want to boot 5.6.12, I first purge everything, then only reinstall 5.6.12, then reboot and try to select old kernel. Not a clean process)

**Comment by bkw777** [comment]
Ukuu had some grub features, and ripping them out with extreme prejudice was one of the first things I did to make this fork.

This util should definitely not involve itself with editing bootloader configuration, especially considerng there are many different possible bootloaders besides grub and no standardized way of configuring them. There are other utils for managing whatever bootloader you have (yes I know it's probably grub2, but, it could also be a dozen other things). Booting is a non-trivial process and it's best left to a dedicated tool whos only job is to deal with all it's complications properly, not some half-baked code in here that could ony ever handle the most common case, and possibly even break something in some unexpected case. Even if it had the feature, no one should trust it or risk using it. 

If there was a "next-boot-chooser" tool that wasn't grub-specific, or even if it was, it might be ok to provide buttons to use it. But all I know of is `grub2-set-default`, but that takes a menu-entry number as it's argument, not a kernel version. We'd have to parse grub2.conf to try to get a correct list of menu entry numbers and matching display values. Maybe that's not too crazy but even that much feels like getting into an unrelated job that some other tool should do right rather than we do half-axxed.

**Comment by bkw777** [comment]
Lacking any ideas, I'm closing this.
