### ISSUE TITLE
Tries to cd to location before download?

### ISSUE THREAD

**Issue by davidc502** [bkw777/mainline#47]
Mainline Kernel Installer 1.0.12

When trying to install kernel 5.7.8 the program tries to cd to the directory where the kernel would be found, but hasn't been downloaded yet.

![Screenshot from 2020-07-09 07-21-27](https://user-images.githubusercontent.com/14110206/87039848-6242ae80-c1b5-11ea-8a2e-46756119395b.png)

**Comment by bkw777** [comment]
Yep, that's messy and avoidable.

**Comment by mikehardy** [comment]
Hi there! Thanks for picking up the torch on UKUU, I use it a lot.

I hit this error, and checking out the code ('Vala'? okay, time for a new language I guess...) it looks like it must not be downloading correctly, but is incorrectly assuming it did, because there are no download messages, just the preparing to install + missing directory

This line is "ok == true" when it shouldn't be:

https://github.com/bkw777/mainline/blob/9920fabd429a39072801742dfed9e858d6c4479a/src/Common/LinuxKernel.vala#L1088

...or else we would definitely have gotten output https://github.com/bkw777/mainline/blob/9920fabd429a39072801742dfed9e858d6c4479a/src/Common/LinuxKernel.vala#L1043

Either the for loop is hitting an empty list or the file existence checks are wrong here then?

https://github.com/bkw777/mainline/blob/9920fabd429a39072801742dfed9e858d6c4479a/src/Common/LinuxKernel.vala#L1032-L1038

I've never tried to turn vala into an executable though and when I `which /usr/bin/mainline` it's a binary so I can't just hack around it quickly unfortunately to diagnose further atm

**Comment by mikehardy** [comment]
might just be a caching error or incorrect state somehow, as I saw this on ukuu but I was having filesystem ownership errors because of stupid things I was doing (mixing command line root vs user vs sudo usage), whereas with mainline it worked after a restart and download of the index

**Comment by bkw777** [comment]
Welcome to the club of not knowing vala. For myself I would also add not liking. ;)

The build directions in the readme.md should work, at least on a debian-based where you can just paste the apt commands, and this whole tool is only for Ubuntu kernels anyway, so that should mean the directions are valid for all users. I just use "make" to build. I put a lot of time into the Makefile so that it does all the right things. But don't worry about it I'm not suggesting you have to wade into that. Debugging vala is about the worst thing I've ever tried to do. Everything is all wrapped and indirect, and it only makes things easier in one direction, writing. It makes it 10x harder trying to backtrack from a problem back to it's cause. If I didn't already have a working starting point, and git, where I can always just back up to the last working point, I would never be able to actually start with a broken thing, figure out what's wrong by interpreting the error message, and make it work.

Mainline is better wrt to the cache and temp handling but still not 100%. I have a refactor in the works but for now the public version still has gaps. For instance, you *should* be able to mix root and non-root commands and there is no excuse for any util to get anything wrong just because of that. The only thing doing that should hurt is winding up with two copies of the cache. Two redundant, wasteful, but perfectly safe and functional and not broken at all copies of the cache. This is temp files 101.

Anyway thanks for taking a look.

**Comment by mikehardy** [comment]
Ah cool - if you've buffed up the build chain, if I stub my toe on anything I'll give it a shot from source
My typical blunt force tool when confronted with whole new worlds like this is ridiculous amounts of logging, if Vala has any sort of thing that allows for log levels and can default to "only info and higher" in release builds then I just go nutty with verbose log entries and add a toggle for people to turn it on for release builds too then have them provide logs (or use same while debugging). But! If you're maintaining a a kernel update utility for linux...I imagine you might have tricks I could learn from and print-debugging isn't a useful idea contribution :-). I do appreciate this tool exists though so if there's a TL:DR; it's thanks for keeping it alive. Cheers

**Comment by bkw777** [comment]
fixed with 06081aaafd025e36b886ea04a788d28a317fc81a

**Comment by mikehardy** [comment]
Just noting my continued appreciate for mainline: thank you!
