### ISSUE TITLE
Fix temp dir / temp file handling

### ISSUE THREAD

**Issue by aljex** [bkw777/mainline#6]
- root process should not write files in a users home dir
- downloading the index to a local temp file is too simple to be failing this often when there is internet access
- if the root and user processes need access to the same info, then store it somewhere central, either world-writable, or only writable by root and only root ever updates the index or cache.
- but, probably there is a way to re-arrange things so that the root and user processes do not both need access to the same files.

    Cache: /home/bkw/.cache/mainline
    Temp: /root/.temp/mainline/AGn2mhQf
    ...
    E: Error moving file /root/.temp/mainline/AGn2mhQf/54hX7Qtl/index.html: No such file or directory
    E: Failed to move file: '/root/.temp/mainline/AGn2mhQf/54hX7Qtl/index.html' → '/home/bkw/.cache/mainline/index.html'

**Comment by bkw777** [comment]
I have improved this a lot, and by now it's actually doing the right thing for most people most of the time. If you only ever use the gui, and don't go out of your way to confuse it by using sudo or pkexec rather than letting it use pkexec itself just when it needs to, then I think it never generates bad files from there any more. If you use the console app without sudo, also all good.

But there are still situations where it will do the wrong thing. If you run the console app from sudo, and it needs to download anything, then it creates root-owned files in your non-root home dir. This can actually be avoided (now). If for some reason you even wanted to use the console app manually or from your own script, you can run --list to download all the indexes and display all the available kernels. You can then run --download with one or more of those versions and it will download those kernels .deb files to cache, all without root still. And finally, you need sudo to run --install, but if you run "sudo mainline --install x.y.z" and x.y.z has already been downloaded, then mainline will not end up creating any directories or files as root. If everything it goes to look for is already there, then it just runs dpkg as root, which is harmless. Mostly, none of that even matters, because youre using the gui app anyway, and that is now doing the right thing.

It also (now) deletes .deb files after installing them, so your ~/.cache directory doesn't grow (much) forever.

And since bad files are no longer being created, --clean-cache actually works. But with no debs, you don't really need to bother with that any more anyway.

Then again, even when it's doing the right thing it's doing it gawdawful inelegantly and inefficiently internally. It's crap.

So it's a lot better, no longer flat out broken in most cases, and generally ok to use now.
But it still needs an even better overhaul, so I'm leaving this issue open.

**Comment by bkw777** [comment]
For one thing, it creates a butt-load of directories in /tmp, and doesn't clean up after itself. You would think that would be pretty simple to fix. I sure did, until I saw the ridiculous ways the code works.I tried really... All I managed to do so far is at east I got it so that each individual function that uses /tmp makes it's own top level dir in /tmp, so that there is never a permissions problem from root and non-root trying to do things in the same dir.

This is ugly and bad hygene and basically crap, but, it's mostly harmless crap today, because /tmp is more and more frequently being done as a tmpfs filesystem in ram, which gets wiped out every reboot, and most systems have a cron job that cleans out /tmp periodically.

**Comment by bkw777** [comment]
massive fixups. using sudo when you don't need it will still cause a mess, but it's cleaning up fully after itself now when used normally (let it ask for root itself when it needs to). No dirs or files are left behind in /tmp. No root-owned files are created in the users ~/.config/...
