### ISSUE TITLE
Zfs don t load kernel RC

### ISSUE THREAD

**Issue by andrea7even** [bkw777/mainline#64]
Hi, Hello. I installed Ubuntu 20.10 Groovy, daily build but I think it doesn't work with Ubuntu Focal either. I installed kernel 5.9 with mainline. With ext4 works, with zfs don’t work. Kernel 5.8 works because it is not in development. Solution?

![1A623FFE-9981-4014-A7E8-CE586779128E](https://user-images.githubusercontent.com/72453254/95363365-a9812e00-08cf-11eb-8b03-0762f1dd02eb.jpeg)

**Comment by Surendrajat** [comment]
Check #55 maybe

**Comment by bkw777** [comment]
Marked invalid because this is essentially expected. There are countless reasons why every single new mainline kernel might not work on a given system, and this is just one of them.

The issue here is that no mainline kernels contain zfs, so you can't run them on a zfs system.

IE, the app is not malfunctioning, it's downloading the .deb files and running dpkg to install or remove them, which is it's only job. Examining the system for possible compatibility problems between the system and the features in the kernel package about to be installed is essentially impossible.
