### ISSUE TITLE
Error need to load kernel first

### ISSUE THREAD

**Issue by s001911** [bkw777/mainline#82]
Hi,

I used Mainline to pull down 5.11.11 and 5.11.10 and they both failed with error:

```
Error need to load kernel first
```

![image](https://user-images.githubusercontent.com/6787817/113812072-c3cd9300-97b0-11eb-92ba-964d47b84b89.png)

**Comment by Kalytis** [comment]
Hi, I just had the same problem with 5.11.13

**Comment by bkw777** [comment]
That error message does not exist anywhere in this app.

However a quick google suggests that it does exist in grub. So look into your bootloader setup.

This app does not touch the bootloader files directly, it only downloads .deb packages and runs dpkg on them. dpkg then ends up editing grub configs, but that's between you and dpkg and the kernel package builders. IE, the package (which we only download, not create) contains instructions for inserting the kernel into bootloaders, and dpkg is responsible for performing those instructions, and the initial ubuntu installer or you yourself are responsible for your grub setup outside of that.

It's essentially impossible to validate bootloader configs programatically, even grub itself can't (otherwise, you would never have gotten that error, grub would have prevented the condition that resulted in it, but as you can see, it didn't), so we don't try. We just don't touch the bootloader at all.

All I can suggest is this, if installing a given kernel package results in an invalid grub config, try:
* uninstall and reinstall that package
* or maybe uninstall, --clean-cache to force a re-download of all the index.html and all associated .deb packages for that kernel, then reinstall
* or just uninstall and avoid that particular version permanently
* or debug the error and figure out what's wrong with your grub config. It could be literally anything. I can't even suggest what it might be, you have to look yourself to find out. Like a missing grub filesystem module, bad block device name, other? Google the error message and read the various examples of what kinds of things it has been for other people for yourself.

**Comment by bkw777** [comment]
If someone can explain more about what this is, feel free to re-open. Until then I'm closing since I don't see it.

**Comment by JonnieCache** [comment]
This is a result of grub refusing to load unsigned kernels, and can be fixed by turning off secure boot, or by signing the kernel yourself.

One could imagine the tool displaying some kind of warning or help message to this effect perhaps?
