### ISSUE TITLE
Change running kernel check logic for Purge

### ISSUE THREAD

**Issue by chaeya** [bkw777/mainline#91]
in src/Common/LinuxKernel.vala

## Test environment

* Result of uname -r : 5.4.0-73-generic
* Versions of installed kernel packages:
5.4.0.73.76
5.4.0-73.82

In this case, the condition k.version_main == kern_running.version_main runs as 5.4.0.73 == 5.4.0.73.76 , 
and the old kernel cannot be deleted because they do not match.

So it would be better to change it like below.
k.version_main.contains(kern_running.version_main)

**Comment by dipenjoshi** [comment]
having the same issue: 
Running kernel: 5.11.0-18-generic
----------------------------------------------------------------------
Found installed: 5.4.2-050402.201912042231
Found installed: 5.7.1-050701.202006071230
Found installed: 5.11.0-17.18
Found installed: 5.11.0.18.19
Found installed: 5.11.0-18.19

E: Could not find running kernel in list!

**Comment by bkw777** [comment]
Matching these non-matching, or multiple-matching version strings is a messy problem I've tried to work on before and so far haven't managed to make it much better.

I agree it's a problem but there is no simple answer I've found yet. Every simple idea just ends up being wrong sometimes, so the choice is to be wrong safely or be wrong unsafely.

In this case we're talking about automatically deleting something.

I would rather fail to delete something automatically than delete the wrong thing automatically.

The user can still manually delete something that didn't get deleted automatically, but removing the wrong kernel can cause a serious non-trivial problem. The machine might no longer boot, or it might boot with no working wifi or no working video. That's a problem I don't ever want to cause, at least not *automatically*.

The real problem is there is actually no proper source of the fundamental key information this app tries to operate on.

There is no actual data field anywhere (like a field in the apt db or a field in a .deb package, that contains clean unambiguous numbers for the parts of what we call a version. All we have are strings that are actually totally free-form. As you see here, 2 different ways to check the version of the same exact thing don't even match each other (uname vs apt).

I started working on an overhaul of how the versions are ingested and stored internally but it got complicated and I got lost and messed it all up (I don't like OO). The version parser is not very good right now. There is one routine that is too simple and tries to do too much. It relies on untrue assumptions and compares strings against each other that came from different sources and were built according to different rules, and assumes that there are rules about how the strings are built when there aren't. Really, there should be seperate parsers for each different source of version strings, and have the different parsers convert the inconsistent version strings into a consistent internal representation. And it probably needs to incorporate more info about a package than just the version string. Like filenames or timestamps of some installed file, anything that can be matched up with something in the apt db later besides just the output of uname which as you see is not good enough.

As for the immediate suggestion to allow a looser match by using contains(), maybe it's ok. I'll have to look at it and think about it to see if that can cause a problem sometimes or not. Probably there is a way to do that loose un-sure match, treat it as just a potential match at first, and just do some other kind of safety check before actually using it.

**Comment by bkw777** [comment]
I think this has been fixed, or at least "good enough", for some time.

It still uses ==, but using different fields now and other parts of the app have changed to fill those fields with more consistent values, and one part is also only matching a substring by splitting on '.', so functionally almost the same.

Although the contains() idea is simpler and I'll probably change it to do that.

It's still not ideal but examples like these seem to have been working ok for a while even if the method is still probably fragile.
