### ISSUE TITLE
Segmentation fault without installed kernels

### ISSUE THREAD

**Issue by edbgon** [bkw777/mainline#92]
For some unrelated testing, I've been running kernels that I've built myself and recently removed the last kernel that was installed using mainline. Running mainline-gtk partially starts, but after finding the installed kernels, it segfaults. I'm assuming this is because it finds no installed kernel in the list.

```
D: query_installed_packages()
D: dir_create(/tmp/.mainline_dN1ti2eg)
D: Created directory: /tmp/.mainline_dN1ti2eg
D: file_write(/tmp/.mainline_dN1ti2eg/16240002992942775502)
D: file_parent(/tmp/.mainline_dN1ti2eg/16240002992942775502)
D: dir_create(/tmp/.mainline_dN1ti2eg)
D: File saved:/tmp/.mainline_dN1ti2eg/16240002992942775502
D: File deleted: /tmp/.mainline_dN1ti2eg/16240002992942775502
D: dir_delete():Deleted: /tmp/.mainline_dN1ti2eg
Found installed: 5.13.0-rc4-edbgon-2
D: Package: linux-image-5.13.0-rc4-edbgon
D: Package: linux-headers-5.13.0-rc4-edbgon
Found installed: 5.13.0-rc6-edbgon-3
D: Package: linux-image-5.13.0-rc6-edbgon
D: Package: linux-headers-5.13.0-rc6-edbgon
----------------------------------------------------------------------
----------------------------------------------------------------------
D: check_updates()
Segmentation fault (core dumped)
```

**Comment by dirkf** [comment]
Same symptom on fresh install Linux Ubuntu 16.04/x86. Mainline 1.0.14.

**Comment by bkw777** [comment]
@dirkf awesome thank you very much for the debug!

**Comment by bkw777** [comment]
Does this fix it for you?
https://github.com/bkw777/mainline/commit/d3b91b092bc470afcdadf8d316559c576dbfad45

I tried rebooting to an ubuntu kernel and removing all mainline kernels and I get no segfault.

But I never got a segfault even before, because even the stock kernels still show up as an installed kernel package, so there is always at least one non-null entry in the list. Even a fresh install should still have at least one stock ubuntu kernel package.

I guess to hit this you'd have to build a kernel from source and boot into it and then remove the last dpkg package, which I didn't try.

**Comment by dirkf** [comment]
No, this (eg) is not found as a pre-existing kernel, presumably because it's not a *mainline* kernel:
```
$ uname -rvis
Linux 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:00 UTC 2021 i686
$
```
I don't have a Vala build chain (well, who does?) but would be happy to try a package based on the fix, which seems innocuous and likely to prevent the crash.

However, I see that the [equivalent line in TeeJee2008's version](https://github.com/teejee2008/ukuu/blob/7a22e188263fc486f711b39f961cdf3c855d854d/src/Common/LinuxKernel.vala#L627) was
```
var kern_running = new LinuxKernel.from_version(LinuxKernel.RUNNING_KERNEL);
```
where `LinuxKernel.RUNNING_KERNEL` is derived from `uname -r`.

So the original update check was based on the running version whereas the proposed fix looks like it would show every mainline kernel as an update when no mainline kernel had been detected as installed, somewhat less helpful. Shouldn't the original behaviour be restored when no mainline kernel is detected as installed?

**Comment by bkw777** [comment]
"I don't have a Vala build chain (well, who does?)"
Which one of the 5 cut & paste lines from the readme was the impossible onerous one?

running_kernel is unrelated to kern_latest_installed.
check_updates() just compares installed kernels packages to available kernel packages. It doesn't care what the running kernel is. That could be anywhere in the list or nowhere.

Whether we want to take the running kernel and treat that as a special case where it's always in the list of installed kernels regardless if we can match it to a package or not is debatable. Might not be a bad idea just for cosmetics, but the proposed fix just ensures the value is a valid type so we don't segfault. The initial value doesn't increase or decrease the scope of the generated lists.

**Comment by dirkf** [comment]
Now that I see the instructions, it's just the 150MB of stuff that I'll never use again: maybe if I had a scratch VM ready and time to set it up and run the build ...

The TeeJee code definitely used to use `kern_running` as the baseline for calculating updates (as in the link above).

If some kernel version is running, it's a reasonable guess that it's actually installed and the checks for installed kernels failed (only having looked for mainline versions?), and therefore updates should be calculated relative to the running version. I suggest that in that case the right thing to do is report that the running kernel version isn't a mainline kernel and warn that updating to a mainline kernel may lose distro functionality.

My reason for wanting to use the utility is to install mainline versions to verify whether some device issue in a distro kernel, or in some later mainline kernel, is fixed in a newer mainline version, as the inevitable response to a bug report is "Please verify that the bug persists in the latest version". I'm not interested in installing historic mainline kernels.

**Comment by bkw777** [comment]
> The TeeJee code definitely used to use `kern_running` as the baseline for calculating updates (as in the link above).
That is of no consequense. The TeeJee code did many terrible and backwards things.

> If some kernel version is running, it's a reasonable guess that it's actually installed and the checks for installed kernels failed (only having looked for mainline versions?), and therefore updates should be calculated relative to the running version. I suggest that in that case the right thing to do is report that the running kernel version isn't a mainline kernel and warn that updating to a mainline kernel may lose distro functionality.

The running kernel is utterly orthagonal to generating the list of available kernels that are newer than the newest installed kernel. 

I shouldn't need to actually provide exampes to explain that, but here you go anyway: The running kernel could have been booted from network, or from an install/rescue thumb drive, or be entirely virtual nothing but an interface as in a vm or container. Even if it IS actually installed on the filesystem, if it came from a self-build then it is as outside our scope of concern as a Windows boot partition is, even though it too is on the local disk and can be booted. The running kernel has no bearing and is of no interest beyond the safety check to avoid trying to uninstall it while you are currently running it.

> My reason for wanting to use the utility is to install mainline versions to verify whether some device issue in a distro kernel, or in some later mainline kernel, is fixed in a newer mainline version, as the inevitable response to a bug report is "Please verify that the bug persists in the latest version". I'm not interested in installing historic mainline kernels.

Me neither, but so what? What do you suppose that to actually resolve to? A list that only even shows the single latest kernel? A list that starts with whatever you happen to be booted to at the moment? That would be not well thought out. It's like saying you never use the letter Q so it shoudn't even be in any of your installed fonts. Never mind the fact that the very nature of the mainline kernels is that they occasionally break things, and the fix is to go back to older ones until it works again. The list doesn't start at the beginning of time. By default it ony starts at the beginning of whatever the current major version is.

**Comment by dirkf** [comment]
OK, I'm convinced as to why you don't want the running kernel as the default baseline for update checks.

That leaves the question why `kernel_latest_installed` wasn't set in a standard Ubuntu respin distro with the `uname` output as above (actually at the time of crash it was probably `Linux 4.4.0-204-generic ...`), or whether its initialisation was *actually* the problem. I'm thinking not, so sorry for the previous incomplete debugging. Having said that, the proposed fix is obviously safer.

Failing command `mainline --check` (my annotations `***` and ellipsis `...`):
```
$ gdb --args /usr/bin/mainline --check
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
...
Reading symbols from /usr/bin/mainline...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/mainline --check
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
mainline 1.0.14
[New Thread 0xb74b3b40 (LWP 16143)]
[New Thread 0xb6cb2b40 (LWP 16144)]
Distribution: LXLE Eclectica 16.04.1 32bit
Architecture: i386
Running kernel: 4.4.0-210-generic
[New Thread 0xb60ffb40 (LWP 16150)]
[New Thread 0xb58feb40 (LWP 16154)]
[New Thread 0xb50fdb40 (LWP 16156)]
Fetching index from kernel.ubuntu.com...
[Thread 0xb50fdb40 (LWP 16156) exited]
[Thread 0xb58feb40 (LWP 16154) exited]
OK
----------------------------------------------------------------------
Found installed: 4.4.0-204.236
Found installed: 4.4.0.210.216
Found installed: 4.4.0-210.242
----------------------------------------------------------------------
----------------------------------------------------------------------

Thread 4 "mainline" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb60ffb40 (LWP 16150)]
0x08053f8f in ?? ()
(gdb) bt
#0  0x08053f8f in ?? ()    *** check_updates() ?
#1  0x08051c56 in ?? ()    *** query_thread() ?
#2  0x0805060f in ?? ()    *** "Thread_main"() ?
#3  0xb7b9c28a in ?? () from /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#4  0xb7b429a4 in ?? () from /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#5  0xb7abe295 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#6  0xb79e81ce in clone () from /lib/i386-linux-gnu/libc.so.6
(gdb) q
A debugging session is active.

	Inferior 1 [process 16139] will be killed.

Quit anyway? (y or n) y
$
 ```
As non-mainline kernels have been found, they [have been added](https://github.com/bkw777/mainline/blob/091a1fb730be26d12a5e32c79d41324f828fe7e6/src/Common/LinuxKernel.vala#L428) to the `kernel_list`, initially populated with all the the kernels listed on the mainline kernel webpage in `load_index()`. The `LinuxKernel` objects added are flagged as installed. But next the `is_installed` flag is assigned again in a [subsequent pass through the list](https://github.com/bkw777/mainline/blob/091a1fb730be26d12a5e32c79d41324f828fe7e6/src/Common/LinuxKernel.vala#L435) comparing each item's `version_package` with the `pkg_version`s stashed during the pass through the installed packages (with 'linux-image' in the name); those are the strings logged in the output.

*As far as I can see,*  `version_package` (default "") is only set in `load_cached_page()`, but surely that hasn't been called for the installed non-mainline kernels? Perhaps not even for mainline kernels not previously installed through the utility? The `LinuxKernel` object [is initialised](https://github.com/bkw777/mainline/blob/091a1fb730be26d12a5e32c79d41324f828fe7e6/src/Common/LinuxKernel.vala#L415) (incidentally, is the previous line redundant, assigning a `String` from a string `printf`ed into `"%s"` -- perhaps I'm missing s/t?), but that doesn't appear to set `version_package` although the required text is used in the `_name` of the constructor (only `kver`, `kname`, `version_main`, `page_uri` and `is_mainline` are set).

Then later in `check_installed()`,
* `kernel_list` is sorted by highest version first
* `kernel_latest_installed` is set to the first item in the list that is flagged as installed, or `null` (without the fix).

And I guess that is where the `null` comes from, the non-mainline installed kernels having been flagged as not installed.

If so, there seem to be two possible fixes:
* assign `version_package` [here](https://github.com/bkw777/mainline/blob/091a1fb730be26d12a5e32c79d41324f828fe7e6/src/Common/LinuxKernel.vala#L415) (possibly other values that might be expected to be set?), or
* skip testing on empty `k.version_package` [here](https://github.com/bkw777/mainline/blob/091a1fb730be26d12a5e32c79d41324f828fe7e6/src/Common/LinuxKernel.vala#L435).

**Comment by bkw777** [comment]
cappelikan's ppa updated last night, so if you apt update you may get the current version now. Does it still segfault on you?

**Comment by dirkf** [comment]
I'm sure it won't if it has your fix, but the PPA (not entirely unreasonably) doesn't have a 16.04 build. My version is from the Ubuntu extra repo.

**Comment by bkw777** [comment]
I might be able to make a deb. I have deb-build working here and it's easy to build for other versions.

**Comment by bkw777** [comment]
I can't build for xenial, at least not trivially. The code currently requires valac >= 0.40 and that is not available in xenial.

**Comment by dirkf** [comment]
Apparently my kind back-porter Rob Savoury managed to build it:
```
$ apt-cache policy mainline
mainline:
  Installed: 1.0.14-0~202107051645~ubuntu16.04.1
  Candidate: 1.0.14-0~202107051645~ubuntu16.04.1
  Version table:
 *** 1.0.14-0~202107051645~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/savoury1/utilities/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
$
```
I'll ping Rob once the issue's resolved.

**Comment by bkw777** [comment]
Looks like https://github.com/bkw777/mainline/issues/76 shows how to build on xenial.
I'll try it and if it works I'll see if I can remove the >= 0.40 requirement for valac in debian/conrol, and add #ifdefs around that line to support both old and new versions.

**Comment by bkw777** [comment]
addd xenial support with c28d8919acab80421e2d12a028b0ceec75548650

**Comment by bkw777** [comment]
fixed with https://github.com/bkw777/mainline/commit/d3b91b092bc470afcdadf8d316559c576dbfad45
