### ISSUE TITLE
error with syncing

### ISSUE THREAD

**Issue by lucserre** [bkw777/mainline#95]
hangs on initial download of index.
Output of CLI (mainline --list)

E: AsyncTask.begin()
E: Failed to execute child process “/tmp/.mainline_0xS6RO3l/script.sh” (Permission denied)
Fetching index from kernel.ubuntu.com...

**Comment by bkw777** [comment]
Is /tmp mounted with noexec ?
```mount |grep /tmp```

Assuming this is the issue, there's two different things to say. 

1:
I think one should be able to run with /tmp noexec. There's really no need for it and no excuse for anything to break if it can't execute executables out of /tmp. So,...
Looks like AsyncTask.vala line 94 is the culprit
The script file is placed as the first (and only) thing in spawn_args
```spawn_args[0] = script_file;```

Then a few lines later spawn_args is used as the command to execute
```
Process.spawn_async_with_pipes(
working_dir, // working dir
spawn_args,  // argv
spawn_env,   // environment
SpawnFlags.SEARCH_PATH,
null,        // child_setup
out child_pid,
out input_fd,
out output_fd,
out error_fd);
```
So I should change that to call "sh scriptname" instead of "scriptname"

However 2:
It's also true that this tool is only for deian-based systems, and debian-based systems don't support running with /tmp noexec. Even apt-get breaks wth /tmp mounted with noexec. It runs aptitude in the background to search for installed packages, and aptitude should be broken also, and nothing I can do can fix that. Isn't your apt/apt-get/aptitude broken also right now? (Or did debian or ubuntu *finally* improve apt so that it no longer breaks on this?

Of course you might also have some other problem entirely so this might all be beside the point.

**Comment by bkw777** [comment]
I've changed it with
https://github.com/bkw777/mainline/commit/a4516a3930bbe1c9d2b08e7572c5a81b4645614b
because there's no reason not to.

But I can only assume you're still broken.

When I remount my own /tmp with noexec, I can't install or remove any packages. This app is still broken by /tmp noexec because apt itself is broken.

There are things you can do in /etc/apt/apf.conf.d to either remount on the fly or tell apt some other directory to use for /tmp but I'm not going to get into that.

**Comment by lucserre** [comment]
I can confirm that my "Pop OS!" installation, has a custom noexec flag on the /tmp mount, and it's mounted as a "tmpfs" filesystem.
I can also confirm that apt works without issue.'
I will try the changes in a little bit and report back.
thanks!

**Comment by lucserre** [comment]
Cloned to local folder, ran 'make', and then ran the mainline-gtk application.  Success.
Note: I still have a tmpfs mount with noexec for my /tmp, but your changes/enhancement did the trick. Well done!
Thanks!

**Comment by bkw777** [comment]
Interesting. Well ok then!
