### ISSUE TITLE
Meaning of "--show-unstable" is unclear, and "--help" is wrong, and there should be a complementary "--hide-unstable"

### ISSUE THREAD

**Issue by tduffy83** [bkw777/mainline#97]
I want to install a release candidate, but the --show-unstable command gives error "Command not specified"

```
:~$ mainline --show-unstable
mainline 1.0.14
Distribution: Ubuntu 21.04
Architecture: amd64
Running kernel: 5.11.0-25-generic
E: Command not specified
E: Run 'mainline --help' to list all commands
```

**Comment by bkw777** [comment]
Looks like --help" is wrong.
"--show-unstable" should be listed under "options" not "commands", it's not a command by itself, it just modifies the bahavior of some commands. You need to use it with a command like "--list"

And, it will only make a difference if you have "Hide unstable and RC kernels" selected in settings in the gui.

IF you have "Hide unstable ..." set in the gui, then you can say ```mainline --list``` or ```mainline --list --show-unstable``` and see a difference in the output. Otherwise you can still run the command, it just won't do anything different since the saved settings already toggled that same bit and all the same kernels would be shown anyway.

Also also... now that I'm looking at this, I think the wording is ambiguous. In the settings screen "Hide unstable" is clear enough, but "show unstable" sounds like "produce a list of unstable kernels" as in only the unstable ones. Maybe the options should be called "--include unstable" ? And there should probably be a matching "--hide unstable". If you're going to have commandline options to override the config file, then why in the world only in one direction?

**Comment by bkw777** [comment]
done: e831a9ba5001984724be985e2110b5c8fe6632fa
